const ACTIVE_COMPANIES = [
  { id: 'allianz', slug: 'allianz', label: 'Allianz', active: true, display_order: 10 },
  { id: 'atm', slug: 'atm', label: 'ATM', active: true, display_order: 20 },
  { id: 'experta', slug: 'experta', label: 'Experta', active: true, display_order: 30 },
  { id: 'mapfre', slug: 'mapfre', label: 'Mapfre', active: true, display_order: 40 },
  { id: 'mercantil_andina', slug: 'mercantil_andina', label: 'Mercantil Andina', active: true, display_order: 45 },
  { id: 'meridional', slug: 'meridional', label: 'Meridional', active: true, display_order: 50 },
  { id: 'provincia', slug: 'provincia', label: 'Provincia', active: true, display_order: 60 },
  { id: 'rivadavia', slug: 'rivadavia', label: 'Rivadavia', active: true, display_order: 70 },
  { id: 'sancor', slug: 'sancor', label: 'Sancor', active: true, display_order: 80 },
  { id: 'smg', slug: 'smg', label: 'SMG', active: true, display_order: 90 },
  { id: 'victoria', slug: 'victoria', label: 'Victoria', active: true, display_order: 100 },
];

const CONCEPTS = [
  concept('medio_pago', 'Medio de pago', 'Medio de pago', 'selector', 'Sí', 'Cabecera masiva gana sobre default.'),
  concept('origen_pago', 'Origen de pago', 'Medio de pago', 'selector', 'No habitual', 'Visible sólo si la compañía lo necesita.'),
  concept('institucion_financiera', 'Institución financiera', 'Medio de pago', 'selector', 'No habitual', 'Visible sólo si acompaña forma de pago.'),
  concept('vigencia_poliza', 'Vigencia de póliza', 'Facturación/Vigencia', 'selector', 'Supervisor', 'Duración contractual.'),
  concept('refacturacion', 'Refacturación', 'Facturación/Vigencia', 'selector', 'Supervisor', 'Frecuencia de recálculo del premio.'),
  concept('cuotas', 'Cuotas', 'Facturación/Vigencia', 'number_or_selector', 'Supervisor', 'Puede derivarse de vigencia/refacturación.'),
  concept('rastreador_alarma', 'Rastreador/Alarma', 'Rastreador/Alarma', 'selector', 'Supervisor', 'Unifica localizador, alarma satelital, equipo de rastreo y prestador satelital.'),
  concept('prestador_satelital', 'Prestador satelital', 'Rastreador/Alarma', 'selector', 'Supervisor', 'Sólo visible en compañías que lo pidan.'),
  concept('uso', 'Uso', 'Riesgo / vehículo', 'selector', 'No habitual', 'Cabecera masiva gana.'),
  concept('ocupacion', 'Ocupación', 'Riesgo / vehículo', 'selector', 'No habitual', 'Sólo visible si la compañía lo pide.'),
  concept('tipo_vehiculo', 'Tipo de vehículo', 'Riesgo / vehículo', 'selector', 'No habitual', 'Absorbe clase/categoría cuando el WS la usa para clasificar vehículo o riesgo.'),
  concept('gnc', 'GNC', 'Riesgo / vehículo', 'selector_plus_amount', 'No', 'Cabecera masiva gana.'),
  concept('garage_guardado', 'Garage / guardado', 'Riesgo / vehículo', 'boolean', 'No habitual', 'Unifica garage y guardado en garage.'),
  concept('asistencia', 'Asistencia', 'Coberturas adicionales', 'selector', 'Supervisor', 'Sólo en compañías con opción comercial.'),
  concept('clausula_ajuste', 'Cláusula de ajuste', 'Ajustes', 'percent_selector', 'Supervisor', 'Cláusula usada para ajustar suma asegurada.'),
  concept('variacion_32080', 'Variación 32080', 'Ajustes', 'percent_selector', 'Supervisor', 'Concepto separado identificado en Victoria.'),
  concept('coeficiente_rc', 'Coeficiente RC', 'Ajustes', 'decimal', 'Supervisor', 'Ingreso numérico, especialmente Rivadavia.'),
  concept('coeficiente_casco', 'Coeficiente Casco', 'Ajustes', 'decimal', 'Supervisor', 'Ingreso numérico, especialmente Rivadavia.'),
  concept('descuento_comercial', 'Descuento comercial', 'Palancas comerciales', 'percent', 'Vendedor', 'Descuento base/comercial por compañía.'),
  concept('descuento_seguro_nuevo', 'Descuento por seguro nuevo', 'Palancas comerciales', 'percent', 'Vendedor', 'Separado porque no aplica igual en renovación.'),
  concept('descuento_no_siniestralidad', 'Descuento por no siniestralidad', 'Palancas comerciales', 'percent', 'Vendedor', 'Separado porque depende de historial.'),
  concept('descuento_especial', 'Descuento especial', 'Palancas comerciales', 'percent', 'Vendedor', 'Independiente del descuento por no siniestralidad.'),
  concept('comision', 'Comisión', 'Palancas comerciales', 'percent', 'Supervisor', 'Editable si WS lo permite.'),
  concept('plan_comercial', 'Plan comercial', 'Palancas comerciales', 'selector', 'Supervisor', 'Hoy identificado para SMG.'),
];

const DEFAULT_VALUES = [
  value('atm', 'medio_pago', 'Tarjeta de crédito', null),
  value('atm', 'vigencia_poliza', 'Anual', 'A'),
  value('atm', 'refacturacion', 'Mensual', null),
  value('atm', 'cuotas', '12', '12', 12),
  value('atm', 'rastreador_alarma', 'Sin Rastreador/Alarma', 'N'),
  value('atm', 'uso', 'Particular', '0101'),
  value('atm', 'gnc', 'Sin GNC', '0', 0),
  value('atm', 'clausula_ajuste', '20%', '020', 20),
  value('atm', 'descuento_comercial', '30%', '30', 30),

  value('allianz', 'medio_pago', 'Tarjeta de crédito', 'T'),
  value('allianz', 'vigencia_poliza', 'Mensual', 'M'),
  value('allianz', 'refacturacion', 'Mensual', 'M'),
  value('allianz', 'cuotas', '1', '1', 1),
  value('allianz', 'rastreador_alarma', 'Sin Rastreador/Alarma', 'false'),
  value('allianz', 'uso', 'Particular', '1'),
  value('allianz', 'gnc', 'Sin GNC', 'ACCESSORY_NONE', 0),
  value('allianz', 'clausula_ajuste', 'Sin ajuste', '0', 0),
  value('allianz', 'descuento_comercial', '-15%', '001/002', 15),

  value('experta', 'medio_pago', 'Tarjeta de crédito', 'debito'),
  value('experta', 'uso', 'Particular', '1'),
  value('experta', 'gnc', 'Sin GNC', 'N', 0),
  value('experta', 'clausula_ajuste', '5%', '5', 5),
  value('experta', 'comision', 'EX0 (20/25%)', 'EX0'),

  value('mapfre', 'medio_pago', 'Tarjeta de crédito', null),
  value('mapfre', 'refacturacion', 'Mensual', 'M'),
  value('mapfre', 'rastreador_alarma', 'Sin Rastreador/Alarma', '0'),
  value('mapfre', 'uso', 'Particular', '1'),
  value('mapfre', 'gnc', 'Sin GNC', '0', 0),
  value('mapfre', 'garage_guardado', 'No', 'false'),
  value('mapfre', 'clausula_ajuste', 'Sin ajuste', null, 0),

  value('mercantil_andina', 'medio_pago', 'Débito automático', 'D'),
  value('mercantil_andina', 'refacturacion', 'Mensual', '1', 1),
  value('mercantil_andina', 'cuotas', '1', '1', 1),
  value('mercantil_andina', 'rastreador_alarma', 'Sin Rastreador/Alarma', '0', 0),
  value('mercantil_andina', 'uso', 'Particular', '1', 1),
  value('mercantil_andina', 'gnc', 'Sin GNC', 'false', 0),
  value('mercantil_andina', 'clausula_ajuste', 'Sin ajuste', '0', 0),
  value('mercantil_andina', 'descuento_comercial', '20%', '20', 20),
  value('mercantil_andina', 'comision', '20%', '20', 20),

  value('provincia', 'medio_pago', 'Tarjeta de crédito', '2'),
  value('provincia', 'origen_pago', 'Visa otros bancos', 'VISO'),
  value('provincia', 'vigencia_poliza', 'Anual', 'A'),
  value('provincia', 'refacturacion', 'Mensual', 'F'),
  value('provincia', 'cuotas', '1 cuota', '1', 1),
  value('provincia', 'rastreador_alarma', 'Sin Rastreador/Alarma', '0'),
  value('provincia', 'uso', 'Particular', '1'),
  value('provincia', 'gnc', 'Sin GNC', '0', 0),
  value('provincia', 'clausula_ajuste', 'Sin ajuste', '0', 0),
  value('provincia', 'descuento_comercial', '1%', '1', 1),
  value('provincia', 'comision', '15%', '15', 15),

  value('rivadavia', 'medio_pago', 'Tarjeta de crédito', 'COBRADOR'),
  value('rivadavia', 'refacturacion', 'Trimestral', 'TRIMESTRAL'),
  value('rivadavia', 'cuotas', '3', '3', 3),
  value('rivadavia', 'rastreador_alarma', 'Sin Rastreador/Alarma', 'SIN_ALARMA'),
  value('rivadavia', 'uso', 'Particular', '1'),
  value('rivadavia', 'tipo_vehiculo', 'Auto', '1'),
  value('rivadavia', 'gnc', 'Sin GNC', 'NO_POSEE_GNC', 0),
  value('rivadavia', 'clausula_ajuste', '30%', '30', 30),
  value('rivadavia', 'coeficiente_rc', '0.90', '0.90', 0.9),
  value('rivadavia', 'coeficiente_casco', '0.90', '0.90', 0.9),

  value('smg', 'medio_pago', 'Tarjeta de crédito', null),
  value('smg', 'refacturacion', 'Mensual', '6'),
  value('smg', 'cuotas', '1', '1', 1),
  value('smg', 'rastreador_alarma', 'Sin Rastreador/Alarma', '0'),
  value('smg', 'uso', 'Particular', '1'),
  value('smg', 'tipo_vehiculo', 'Auto', '1'),
  value('smg', 'gnc', 'Sin GNC', '0', 0),
  value('smg', 'clausula_ajuste', 'Sin cláusula', '1', 0),
  value('smg', 'descuento_comercial', '-15%', '-15', 15),
  value('smg', 'asistencia', 'Sí', '-1'),
  value('smg', 'plan_comercial', 'Plan Normal', '1'),

  value('sancor', 'vigencia_poliza', 'Anual', '1'),
  value('sancor', 'refacturacion', 'Mensual', '5'),
  value('sancor', 'cuotas', 'Sin cuotas (mensual)', '0', 0),
  value('sancor', 'uso', 'Particular', '2'),
  value('sancor', 'gnc', 'Sin GNC', '0', 0),
  value('sancor', 'garage_guardado', 'Sí', '1'),
  value('sancor', 'clausula_ajuste', 'Ninguna', null, 0),
  value('sancor', 'descuento_no_siniestralidad', '99', '99', 99),
  value('sancor', 'descuento_especial', '48', '48', 48),

  value('victoria', 'medio_pago', 'Tarjeta de crédito', '2'),
  value('victoria', 'vigencia_poliza', 'Trimestral', '4'),
  value('victoria', 'refacturacion', 'Mensual', 'Mensual'),
  value('victoria', 'cuotas', 'Contado', '1', 1),
  value('victoria', 'rastreador_alarma', 'Sin Rastreador/Alarma', 'false|0'),
  value('victoria', 'uso', 'Particular', '1'),
  value('victoria', 'gnc', 'Sin GNC', 'false', 0),
  value('victoria', 'clausula_ajuste', '10%', '2', 10),
  value('victoria', 'variacion_32080', '-10%', '6', -10),
  value('victoria', 'descuento_comercial', '-10%', '-10', 10),
  value('victoria', 'descuento_seguro_nuevo', '25%', '25', 25),

  value('meridional', 'ocupacion', 'No informa', 'NO_INFORMA'),
  value('meridional', 'medio_pago', 'Tarjeta de crédito', 'TA'),
  value('meridional', 'refacturacion', 'Mensual', '3'),
  value('meridional', 'cuotas', '1', '1', 1),
  value('meridional', 'rastreador_alarma', 'Sin Rastreador/Alarma', '1'),
  value('meridional', 'uso', 'Particular', '1'),
  value('meridional', 'gnc', 'Sin GNC', 'ACCESSORY_NONE', 0),
  value('meridional', 'clausula_ajuste', 'Sin ajuste', '1', 0),
  value('meridional', 'comision', '18%', '18', 18),
];

const OPTIONS = [
  option('atm', 'medio_pago', 'Tarjeta de crédito', null),
  option('atm', 'vigencia_poliza', 'Anual', 'A'),
  option('atm', 'refacturacion', 'Mensual', null),
  option('atm', 'cuotas', '12', '12', 12),
  option('atm', 'rastreador_alarma', 'Sin Rastreador/Alarma', 'N'),
  option('atm', 'rastreador_alarma', 'Con Rastreador/Alarma', 'S'),
  option('atm', 'gnc', 'Sin GNC', '0'),
  option('atm', 'gnc', 'Con GNC', '1'),
  ...optionsFromList('atm', 'uso', [
    ['AUTO/JEEP/SUV PARTICULARES Y FAMILIARES', '0101'],
    ['AUTO/JEEP/SUV COMERCIAL', '010102'],
    ['AUTO TS PARTICULAR', '010103'],
    ['AUTO TS COMERCIAL', '010104'],
    ['ALTA GAMA PARTICULAR', '1717'],
    ['PICK UP A PARTICULAR', '1110'],
    ['PICK UP A COMERCIAL TRANSPORTE DE BIENES', '1212'],
    ['JEEP Y PICK UP B PARTICULAR', '1414'],
    ['JEEP Y PICK UP B COMERCIAL TRANSPORTE DE BIENES', '1515'],
    ['MOTO HASTA 125 C.C. PARTICULAR', '4262'],
    ['MOTO HASTA 125 C.C. COMERCIAL', '5272'],
    ['MOTO DE 126 A 250 C.C. PARTICULAR', '4263'],
    ['MOTO DE 126 A 250 C.C. COMERCIAL', '5273'],
    ['MOTO DE MAS DE 250 C.C. PARTICULAR', '4264'],
    ['MOTO DE MAS DE 250 C.C. COMERCIAL', '5274'],
    ['CUATRICICLO ATV PARTICULAR', '6265'],
    ['MOTO ELECTRICA PARTICULAR', '2261'],
    ['MOTO ELECTRICA COMERCIAL', '5271'],
    ['CUATRICICLO UTV PARTICULAR', '6266'],
    ['MOTO BLACK PARTICULAR', '060701'],
    ['MOTO BLACK COMERCIAL', '060702'],
    ['TRICICLO PARTICULAR', '4268'],
    ['TRICICLO COMERCIAL', '5278'],
    ['BICICLETA ELECTRICA PARTICULAR', '4561'],
    ['SCOOTER PARTICULAR', '061001'],
    ['SCOOTER COMERCIAL', '061002'],
    ['MOTOS HONDA HASTA 125 CC.', '061101'],
    ['TRAILER', '1818'],
  ]),
  option('atm', 'clausula_ajuste', 'Sin ajuste', '0', 0),
  option('atm', 'clausula_ajuste', '10%', '010', 10),
  option('atm', 'clausula_ajuste', '20%', '020', 20),
  ...optionsFromList('atm', 'descuento_comercial', [
    ['0%', '0', 0],
    ['5%', '5', 5],
    ['10%', '10', 10],
    ['15%', '15', 15],
    ['20%', '20', 20],
    ['25%', '25', 25],
    ['30%', '30', 30],
  ]),

  option('allianz', 'medio_pago', 'Tarjeta de crédito', 'T'),
  option('allianz', 'medio_pago', 'Efectivo', 'E'),
  option('allianz', 'vigencia_poliza', 'Mensual', 'M'),
  option('allianz', 'vigencia_poliza', 'Semestral', 'S'),
  option('allianz', 'vigencia_poliza', 'Anual', 'A'),
  option('allianz', 'vigencia_poliza', 'Período', 'P'),
  option('allianz', 'refacturacion', 'Mensual', 'M'),
  option('allianz', 'cuotas', '1', '1', 1),
  option('allianz', 'rastreador_alarma', 'Sin Rastreador/Alarma', 'false'),
  option('allianz', 'rastreador_alarma', 'Con Rastreador/Alarma', 'true'),
  option('allianz', 'uso', 'Particular', '1'),
  option('allianz', 'uso', 'Comercial', '2'),
  option('allianz', 'uso', 'Local', '3'),
  option('allianz', 'uso', 'Rutero', '4'),
  option('allianz', 'gnc', 'Sin GNC', 'ACCESSORY_NONE'),
  option('allianz', 'gnc', 'Con GNC', 'ACCESSORY_GNC'),
  option('allianz', 'clausula_ajuste', 'Sin ajuste', '0', 0),
  ...optionsFromList('allianz', 'descuento_comercial', [
    ['-15%', '-15', 15],
    ['-10%', '-10', 10],
    ['-5%', '-5', 5],
    ['0%', '0', 0],
    ['5%', '5', 5],
    ['10%', '10', 10],
    ['15%', '15', 15],
  ]),

  option('experta', 'medio_pago', 'Tarjeta de crédito', 'debito'),
  option('experta', 'medio_pago', 'CBU / débito en cuenta', 'debito'),
  option('experta', 'medio_pago', 'Efectivo', 'efectivo'),
  option('experta', 'uso', 'Particular', '1'),
  option('experta', 'uso', 'Comercial', '10'),
  option('experta', 'gnc', 'Sin GNC', 'N'),
  option('experta', 'gnc', 'Con GNC', '501'),
  option('experta', 'clausula_ajuste', '5%', '5', 5),
  option('experta', 'clausula_ajuste', '10%', '10', 10),
  option('experta', 'clausula_ajuste', '20%', '20', 20),
  option('experta', 'comision', 'EX0 (20/25%)', 'EX0'),

  option('mapfre', 'medio_pago', 'Tarjeta de crédito', 'TC'),
  option('mapfre', 'medio_pago', 'CBU / débito en cuenta', 'DC'),
  option('mapfre', 'medio_pago', 'Efectivo', 'AG'),
  option('mapfre', 'medio_pago', 'Productor', 'PR'),
  option('mapfre', 'refacturacion', 'Mensual', 'M'),
  option('mapfre', 'rastreador_alarma', 'Sin Rastreador/Alarma', '0'),
  option('mapfre', 'rastreador_alarma', 'Con Rastreador/Alarma', '1'),
  option('mapfre', 'uso', 'Particular', '1'),
  option('mapfre', 'uso', 'Comercial', '7'),
  option('mapfre', 'gnc', 'Sin GNC', '0'),
  option('mapfre', 'gnc', 'Con GNC', '1'),
  option('mapfre', 'garage_guardado', 'Sí', 'true'),
  option('mapfre', 'garage_guardado', 'No', 'false'),
  option('mapfre', 'clausula_ajuste', 'Sin ajuste', null, 0),

  option('mercantil_andina', 'medio_pago', 'Débito automático', 'D'),
  option('mercantil_andina', 'medio_pago', 'Convenio / tarjeta', 'C'),
  option('mercantil_andina', 'refacturacion', 'Mensual', '1', 1),
  option('mercantil_andina', 'cuotas', '1', '1', 1),
  option('mercantil_andina', 'rastreador_alarma', 'Sin Rastreador/Alarma', '0', 0),
  option('mercantil_andina', 'rastreador_alarma', 'Con Rastreador/Alarma', '1', 1),
  option('mercantil_andina', 'uso', 'Particular', '1', 1),
  option('mercantil_andina', 'gnc', 'Sin GNC', 'false', 0),
  option('mercantil_andina', 'gnc', 'Con GNC', 'true', 1),
  ...optionsFromList('mercantil_andina', 'clausula_ajuste', [
    ['Sin ajuste', '0', 0],
  ]),
  ...optionsFromList('mercantil_andina', 'descuento_comercial', [
    ['0%', '0', 0],
    ['5%', '5', 5],
    ['10%', '10', 10],
    ['15%', '15', 15],
    ['20%', '20', 20],
  ]),
  ...optionsFromList('mercantil_andina', 'comision', [
    ['10%', '10', 10],
    ['15%', '15', 15],
    ['20%', '20', 20],
  ]),

  option('provincia', 'medio_pago', 'Tarjeta de crédito', '2'),
  option('provincia', 'medio_pago', 'CBU / débito en cuenta', '3'),
  option('provincia', 'medio_pago', 'Efectivo / caja', '1'),
  option('provincia', 'origen_pago', 'Visa otros bancos', 'VISO'),
  option('provincia', 'origen_pago', 'Débito directo Provincia', 'PDIR'),
  option('provincia', 'origen_pago', 'Caja / efectivo', 'A'),
  option('provincia', 'vigencia_poliza', 'Anual', 'A'),
  option('provincia', 'refacturacion', 'Mensual', 'F'),
  option('provincia', 'cuotas', '1 cuota', '1', 1),
  option('provincia', 'rastreador_alarma', 'Sin Rastreador/Alarma', '0'),
  option('provincia', 'rastreador_alarma', 'Con Rastreador/Alarma', '1'),
  option('provincia', 'uso', 'Particular', '1'),
  option('provincia', 'uso', 'Particular exclusivamente', '79'),
  option('provincia', 'uso', 'Uso oficial', '9'),
  option('provincia', 'uso', 'Trabajo rural', '10'),
  option('provincia', 'uso', 'Trabajo no rural', '11'),
  option('provincia', 'uso', 'Comercial', '42'),
  option('provincia', 'uso', 'Uso comercial', '21'),
  option('provincia', 'uso', 'Comercial transporte de carga general', '21'),
  option('provincia', 'uso', 'Comercial transporte de carga peligrosa', '22'),
  option('provincia', 'uso', 'Alquiler sin chofer', '37'),
  option('provincia', 'uso', 'Auxilio mecánico', '12'),
  option('provincia', 'uso', 'Servicio especial pasajeros', '64'),
  option('provincia', 'gnc', 'Sin GNC', '0'),
  option('provincia', 'gnc', 'Con GNC', 'montoAccesorios'),
  option('provincia', 'clausula_ajuste', 'Sin ajuste', '0', 0),
  option('provincia', 'clausula_ajuste', '10%', '10', 10),
  ...optionsFromList('provincia', 'descuento_comercial', [
    ['1%', '1', 1],
    ['5%', '5', 5],
    ['10%', '10', 10],
    ['15%', '15', 15],
    ['20%', '20', 20],
    ['22%', '22', 22],
    ['25%', '25', 25],
  ]),
  option('provincia', 'comision', '15%', '15', 15),
  option('provincia', 'comision', '20%', '20', 20),

  option('rivadavia', 'medio_pago', 'Tarjeta de crédito', 'COBRADOR'),
  option('rivadavia', 'medio_pago', 'Efectivo / cobrador', 'COBRADOR'),
  option('rivadavia', 'refacturacion', 'Trimestral', 'TRIMESTRAL'),
  option('rivadavia', 'cuotas', '3', '3', 3),
  option('rivadavia', 'rastreador_alarma', 'Sin Rastreador/Alarma', 'SIN_ALARMA'),
  option('rivadavia', 'rastreador_alarma', 'Con Rastreador/Alarma', 'CON_ALARMA'),
  option('rivadavia', 'uso', 'Particular', '1'),
  option('rivadavia', 'uso', 'Taxi', '2'),
  option('rivadavia', 'uso', 'Remis', '3'),
  option('rivadavia', 'uso', 'Comercial / Transporte de bienes', '6'),
  option('rivadavia', 'uso', 'Reparto / Mensajería', '15'),
  option('rivadavia', 'tipo_vehiculo', 'Auto', '1'),
  option('rivadavia', 'tipo_vehiculo', 'Pick Up Clase A', '6'),
  option('rivadavia', 'tipo_vehiculo', 'Pick Up Clase B', '8'),
  option('rivadavia', 'gnc', 'Sin GNC', 'NO_POSEE_GNC'),
  option('rivadavia', 'gnc', 'Con GNC', 'POSEE_GNC'),
  option('rivadavia', 'clausula_ajuste', '10%', '10', 10),
  option('rivadavia', 'clausula_ajuste', '20%', '20', 20),
  option('rivadavia', 'clausula_ajuste', '30%', '30', 30),
  option('rivadavia', 'clausula_ajuste', '40%', '40', 40),
  option('rivadavia', 'clausula_ajuste', '50%', '50', 50),
  ...optionsFromList('rivadavia', 'coeficiente_rc', [
    ['1', '1', 1],
    ['0.9', '0.9', 0.9],
    ['0.8', '0.8', 0.8],
  ]),
  ...optionsFromList('rivadavia', 'coeficiente_casco', [
    ['1', '1', 1],
    ['0.9', '0.9', 0.9],
    ['0.8', '0.8', 0.8],
  ]),

  option('smg', 'medio_pago', 'Tarjeta de crédito', null),
  option('smg', 'refacturacion', 'Mensual', '6'),
  option('smg', 'cuotas', '1', '1', 1),
  option('smg', 'rastreador_alarma', 'Sin Rastreador/Alarma', '0'),
  option('smg', 'rastreador_alarma', 'Lo Jack', '2'),
  option('smg', 'rastreador_alarma', 'Tracer', '3'),
  option('smg', 'rastreador_alarma', 'Pointer', '5'),
  option('smg', 'rastreador_alarma', 'Ituran', '6'),
  option('smg', 'rastreador_alarma', 'Ubicar', '7'),
  option('smg', 'rastreador_alarma', 'Lo Jack a cargo compañía', '14'),
  option('smg', 'rastreador_alarma', 'Tracer a cargo compañía', '20'),
  option('smg', 'rastreador_alarma', 'Micrograbado', '46'),
  option('smg', 'uso', 'Particular', '1'),
  option('smg', 'uso', 'Comercial', '6'),
  option('smg', 'tipo_vehiculo', 'Auto', '1'),
  option('smg', 'tipo_vehiculo', 'Moto', '2'),
  option('smg', 'gnc', 'Sin GNC', '0'),
  option('smg', 'gnc', 'Con GNC', '1'),
  option('smg', 'clausula_ajuste', 'Sin cláusula', '1', 0),
  option('smg', 'clausula_ajuste', '10%', '2', 10),
  option('smg', 'clausula_ajuste', '20%', '3', 20),
  ...optionsFromList('smg', 'descuento_comercial', [
    ['-15%', '-15', 15],
    ['-10%', '-10', 10],
    ['-5%', '-5', 5],
    ['0%', '0', 0],
    ['5%', '5', 5],
    ['10%', '10', 10],
  ]),
  option('smg', 'asistencia', 'Sí', '-1'),
  option('smg', 'asistencia', 'No', '0'),
  option('smg', 'plan_comercial', 'Plan Normal', '1'),

  option('sancor', 'vigencia_poliza', 'Anual', '1'),
  option('sancor', 'vigencia_poliza', 'Semestral', '2'),
  option('sancor', 'vigencia_poliza', 'Trimestral', '3'),
  option('sancor', 'refacturacion', 'Mensual', '5'),
  option('sancor', 'cuotas', 'Sin cuotas (mensual)', '0', 0),
  option('sancor', 'uso', 'Particular', '2'),
  option('sancor', 'uso', 'Particular y/o comercial', '4'),
  option('sancor', 'gnc', 'Sin GNC', '0'),
  option('sancor', 'gnc', 'Con GNC', '1'),
  option('sancor', 'garage_guardado', 'Sí', '1'),
  option('sancor', 'garage_guardado', 'No', '2'),
  option('sancor', 'clausula_ajuste', 'Ninguna', null, 0),

  option('victoria', 'medio_pago', 'Tarjeta de crédito', '2'),
  option('victoria', 'medio_pago', 'CBU / débito en cuenta', '3'),
  option('victoria', 'medio_pago', 'Efectivo', '1'),
  option('victoria', 'vigencia_poliza', 'Mensual', '12'),
  option('victoria', 'vigencia_poliza', 'Cuatrimestral', '3'),
  option('victoria', 'vigencia_poliza', 'Trimestral', '4'),
  option('victoria', 'refacturacion', 'Mensual', 'Mensual'),
  option('victoria', 'cuotas', 'Contado', '1', 1),
  option('victoria', 'rastreador_alarma', 'Sin Rastreador/Alarma', 'false|0'),
  option('victoria', 'rastreador_alarma', 'Tracer', 'true|1'),
  option('victoria', 'rastreador_alarma', 'Ituran', 'true|2'),
  option('victoria', 'rastreador_alarma', 'Datatrak', 'true|3'),
  option('victoria', 'rastreador_alarma', 'Ubicar', 'true|4'),
  option('victoria', 'rastreador_alarma', 'Lo Jack', 'true|5'),
  option('victoria', 'uso', 'Particular', '1'),
  option('victoria', 'uso', 'Comercial', '2'),
  option('victoria', 'uso', 'Transporte de bienes', '8'),
  option('victoria', 'uso', 'Trabajos rurales', '9'),
  option('victoria', 'gnc', 'Sin GNC', 'false'),
  option('victoria', 'gnc', 'Con GNC', 'true'),
  option('victoria', 'clausula_ajuste', '0%', '1', 0),
  option('victoria', 'clausula_ajuste', '10%', '2', 10),
  option('victoria', 'clausula_ajuste', '20%', '3', 20),
  option('victoria', 'clausula_ajuste', '30%', '4', 30),
  option('victoria', 'variacion_32080', '-15%', '1', -15),
  option('victoria', 'variacion_32080', '-10%', '6', -10),
  option('victoria', 'variacion_32080', '-5%', '11', -5),
  option('victoria', 'variacion_32080', '0%', '16', 0),
  option('victoria', 'variacion_32080', '5%', '21', 5),
  option('victoria', 'variacion_32080', '10%', '26', 10),
  ...optionsFromList('victoria', 'descuento_comercial', [
    ['-10%', '-10', 10],
    ['-5%', '-5', 5],
    ['0%', '0', 0],
    ['5%', '5', 5],
    ['10%', '10', 10],
  ]),
  option('victoria', 'descuento_seguro_nuevo', '25%', '25', 25),

  option('meridional', 'ocupacion', 'No informa', 'NO_INFORMA'),
  option('meridional', 'medio_pago', 'Tarjeta de crédito', 'TA'),
  option('meridional', 'medio_pago', 'CBU', 'BA'),
  option('meridional', 'medio_pago', 'Débito directo', 'DD'),
  option('meridional', 'medio_pago', 'Débito en cuenta', 'DC'),
  option('meridional', 'medio_pago', 'Efectivo', 'EF'),
  option('meridional', 'medio_pago', 'Pago Fácil', 'PR'),
  option('meridional', 'refacturacion', 'Mensual', '3'),
  option('meridional', 'cuotas', '1', '1', 1),
  option('meridional', 'rastreador_alarma', 'Sin Rastreador/Alarma', '1'),
  option('meridional', 'rastreador_alarma', 'Ubicar - A cargo del Cliente', '16'),
  option('meridional', 'rastreador_alarma', 'Ubicar - A cargo de la Compañía', '17'),
  option('meridional', 'rastreador_alarma', 'Pointer - A cargo del Cliente', '23'),
  option('meridional', 'rastreador_alarma', 'Pointer - A cargo de la Compañía', '24'),
  option('meridional', 'rastreador_alarma', 'Lo-Jack - A cargo del Cliente', '25'),
  option('meridional', 'rastreador_alarma', 'Lo-Jack - A cargo de la Compañía', '26'),
  option('meridional', 'rastreador_alarma', 'Ituran - A cargo del Cliente', '32'),
  option('meridional', 'rastreador_alarma', 'Ituran - A cargo de la Compañía', '33'),
  option('meridional', 'uso', 'Particular', '1'),
  option('meridional', 'uso', 'Comercial', '2'),
  option('meridional', 'uso', 'Carga peligrosa', '4'),
  option('meridional', 'uso', 'Carga peligrosa PK', '5'),
  option('meridional', 'uso', 'Comercial carga general', '28'),
  option('meridional', 'uso', 'Comercial carga peligrosa', '29'),
  option('meridional', 'gnc', 'Sin GNC', 'ACCESSORY_NONE'),
  option('meridional', 'gnc', 'Con GNC', 'ACCESSORY_GNC'),
  option('meridional', 'clausula_ajuste', 'Sin ajuste', '1', 0),
  option('meridional', 'clausula_ajuste', '20%', '2', 20),
  option('meridional', 'clausula_ajuste', '30%', '3', 30),
  option('meridional', 'clausula_ajuste', '40%', '4', 40),
  option('meridional', 'clausula_ajuste', '50%', '5', 50),
  option('meridional', 'comision', '18%', '18', 18),
];

const OVERRIDE_RULES = [
  rule('allianz', 'descuento_comercial', 'vendedor', true, 0, 15, 'Puntual por cotización.'),
  rule('allianz', 'clausula_ajuste', 'supervisor', true, 0, 0, 'WS expone clausulaDeAjuste; documentación local sólo confirma 0/sin ajuste.'),
  rule('atm', 'descuento_comercial', 'vendedor', true, 0, 30, 'Campo histórico bonificacion tratado como descuento comercial.'),
  rule('atm', 'clausula_ajuste', 'supervisor', true, 0, 20, 'Permitir 0/sin ajuste. Default PPT/config actual 20%.'),
  rule('experta', 'clausula_ajuste', 'supervisor', true, 5, 20, 'API validada en vivo: sólo admite 5%, 10% o 20%. Omitir/null aplica 5% por defecto; 0 o vacío son rechazados.'),
  rule('mapfre', 'clausula_ajuste', 'supervisor', true, 0, 0, 'Request SOAP expone porcentajeAjuste; ejemplos locales lo envían vacío.'),
  rule('mercantil_andina', 'clausula_ajuste', 'supervisor', true, 0, 0, 'La API acepta otros números pero los normaliza a 0 sin modificar suma ni premio. Sólo se habilita Sin ajuste.'),
  rule('mercantil_andina', 'descuento_comercial', 'vendedor', true, 0, 20, 'Campo bonificacion. Valores probados en vivo: 0, 5, 10, 15 y 20.'),
  rule('mercantil_andina', 'comision', 'supervisor', true, 10, 20, 'Valores probados en vivo: 10, 15 y 20.'),
  rule('meridional', 'clausula_ajuste', 'supervisor', true, 0, 50, 'Catálogo local IdClausulaAjuste: 0%, 20%, 30%, 40%, 50%.'),
  rule('provincia', 'descuento_comercial', 'vendedor', true, 0, 25, '40088_bonifAdicional. Default operativo 1%; rango promocional documentado hasta 25%.'),
  rule('provincia', 'comision', 'supervisor', true, 15, 20, 'Provincia acepta 15 y 20 para la relación/productor probada; 0.15 y 18 devuelven error funcional 27309.'),
  rule('provincia', 'clausula_ajuste', 'supervisor', true, 0, 10, 'WS define 40550_clausulaAjuste como valor porcentual; ejemplo local usa 10%.'),
  rule('rivadavia', 'clausula_ajuste', 'supervisor', true, 10, 50, 'Request actual envía porcentajeAjuste; WS SOAP responde ajuste permitido entre 10 y 50%.'),
  rule('rivadavia', 'coeficiente_rc', 'supervisor', true, 0.8, 1, 'SOAP histórico: CoefRC. Opciones validadas: 1, 0.9, 0.8. Debe sincronizarse con CoefCasco cuando baja de 0.9.'),
  rule('rivadavia', 'coeficiente_casco', 'supervisor', true, 0.8, 1, 'SOAP histórico: CoefCasco. Opciones validadas: 1, 0.9, 0.8. Debe sincronizarse con CoefRC cuando baja de 0.9.'),
  rule('smg', 'descuento_comercial', 'vendedor', true, 0, 15, 'Ajuste de prima como palanca comercial.'),
  rule('smg', 'clausula_ajuste', 'supervisor', true, 0, 20, 'WS SMG V1 Tabla 1: S/C, 10%, 20%.'),
  rule('victoria', 'descuento_comercial', 'vendedor', true, 0, 10, 'discount_commercial: negativo=descuento, positivo=recargo.'),
  rule('victoria', 'clausula_ajuste', 'supervisor', true, 0, 30, 'Catálogo vivo Victoria: 0%, 10%, 20%, 30%.'),
  rule('victoria', 'variacion_32080', 'supervisor', true, -15, 10, 'Catálogo vivo Victoria -15% a +10%; UI simplificada en pasos de 5%.'),
  rule('victoria', 'descuento_seguro_nuevo', 'vendedor', true, 0, 25, 'Sólo cotización nueva.'),
  rule('sancor', 'descuento_no_siniestralidad', 'vendedor', true, 0, 99, 'Máximo inicial PPT.'),
  rule('sancor', 'descuento_especial', 'vendedor', true, 0, 48, 'Máximo inicial PPT.'),
  rule('meridional', 'comision', 'supervisor', true, null, null, 'WSCAR usa PorcComision; default operativo 18%.'),
  rule('mapfre', 'garage_guardado', 'supervisor', true, null, null, 'WS cotizar: guardaGGe true/false.'),
  rule('sancor', 'garage_guardado', 'supervisor', true, null, null, 'ScoringTypeId=3; SelectedOptionId 1=Sí, 2=No.'),
  rule('smg', 'asistencia', 'supervisor', true, null, null, 'AsistMecanica: -1 con asistencia, 0 sin asistencia.'),
];

const WS_MAPPINGS = [
  mapping('atm', 'rastreador_alarma', 'rastreo', 'N', 'PPT + adapter'),
  mapping('allianz', 'rastreador_alarma', 'VehiculoACotizar.tieneAlarma/codigoTipoAlarma', 'false/true + LA', 'Allianz ejemplos WS'),
  mapping('atm', 'uso', 'vehiculo.uso', 'ws_au_usos', 'ATM ws_au_usos FTP'),
  mapping('atm', 'vigencia_poliza', 'usuario.plan', 'get_plans combina vigencia/facturacion/cuotas/forma de pago', 'ATM Cotizador_WS_V1.9'),
  mapping('atm', 'refacturacion', 'usuario.plan', 'get_plans combina vigencia/facturacion/cuotas/forma de pago', 'ATM Cotizador_WS_V1.9 + data/atm/diccionarios/vigencia.json'),
  mapping('atm', 'cuotas', 'usuario.plan', 'derivado de vigencia/refacturacion', 'ATM Cotizador_WS_V1.9 + data/atm/diccionarios/vigencia.json'),
  mapping('atm', 'gnc', 'Vehicle.GNCInformation.HasGNC/GNCValue', '0/1 + monto', 'ATM ejemplo WS EJ 2'),
  mapping('atm', 'clausula_ajuste', 'ajuste', '0/sin ajuste o 020', 'WS examples + PPT/data'),
  mapping('atm', 'descuento_comercial', 'bonificacion', '30', 'PPT + adapter'),
  mapping('allianz', 'vigencia_poliza', 'tipoDePoliza', 'M/S/A/P', 'Allianz Especificación WS Vehículos Cotizador'),
  mapping('allianz', 'refacturacion', 'tipoDePoliza', 'M por default actual', 'Allianz adapter resolveAllianzPayment'),
  mapping('allianz', 'cuotas', 'cantidadDeCuotas', '1/6/12 según tipoDePoliza y medioDePago', 'Allianz adapter resolveAllianzPayment'),
  mapping('allianz', 'uso', 'VehiculoACotizar.codigoDeUso', 'ObtenerUsosVehiculo', 'Allianz Operación ObtenerUsosVehiculo'),
  mapping('allianz', 'gnc', 'VehiculoACotizar.ListaAccesorios.codigoAccesorio/sumaAccesorio', 'ACCESSORY_GNC + monto', 'Allianz Especificación WS Vehículos Cotizador: accesorios por catálogo'),
  mapping('allianz', 'clausula_ajuste', 'CondicionesContratacion.clausulaDeAjuste', '0', 'Allianz Especificación WS Vehículos Cotizador'),
  mapping('experta', 'uso', 'uso', 'RequestCotizacion.uso', 'Experta Swagger RequestCotizacion'),
  mapping('experta', 'gnc', 'gnc/valorGnc', 'N o 501 + monto', 'Experta Swagger RequestCotizacion + adapter'),
  mapping('experta', 'clausula_ajuste', 'porcentajeAjuste', '5/10/20', 'Experta API validada en vivo + ejemplos'),
  mapping('experta', 'comision', 'modalidad', 'EX0', 'Experta adapter: modalidad default EX0'),
  mapping('mapfre', 'refacturacion', 'tipoFacturacion', 'M', 'Mapfre request SOAP'),
  mapping('mapfre', 'rastreador_alarma', 'conLocalizador', '0/1', 'Mapfre request SOAP'),
  mapping('mapfre', 'uso', 'usoVehiculo', '1/7 según diccionario local', 'Mapfre request SOAP + data/mapfre/diccionarios/uso.json'),
  mapping('mapfre', 'gnc', 'conGNC/valorGNC', '0/1 + monto', 'Mapfre request SOAP'),
  mapping('mapfre', 'garage_guardado', 'guardaGGe', 'true/false', 'Mapfre request SOAP'),
  mapping('mapfre', 'clausula_ajuste', 'porcentajeAjuste', 'vacío/sin ajuste', 'Mapfre request SOAP ejemplos'),
  mapping('mercantil_andina', 'medio_pago', 'pago.tipo_pago', 'D/C', 'Mercantil Andina API validada en vivo'),
  mapping('mercantil_andina', 'refacturacion', 'periodo', '1=Mensual', 'Mercantil Andina API validada en vivo'),
  mapping('mercantil_andina', 'cuotas', 'cuotas', '1', 'Mercantil Andina API validada en vivo'),
  mapping('mercantil_andina', 'rastreador_alarma', 'vehiculo.rastreo', '0/1', 'Mercantil Andina API validada en vivo'),
  mapping('mercantil_andina', 'uso', 'vehiculo.uso', '1=Particular', 'Mercantil Andina API validada para automóvil particular'),
  mapping('mercantil_andina', 'gnc', 'vehiculo.gnc', 'false/true', 'Mercantil Andina API validada en vivo; el request no expone suma GNC'),
  mapping('mercantil_andina', 'clausula_ajuste', 'ajuste_suma', '0=Sin ajuste', 'Mercantil Andina API validada en vivo: otros valores fueron ignorados'),
  mapping('mercantil_andina', 'descuento_comercial', 'bonificacion', '0/5/10/15/20', 'Mercantil Andina API validada en vivo'),
  mapping('mercantil_andina', 'comision', 'comision', '10/15/20', 'Mercantil Andina API validada en vivo'),
  mapping('provincia', 'refacturacion', 'tipoFacturacion', 'F', 'Provincia WS: tipoFacturacion'),
  mapping('provincia', 'cuotas', 'planDePago', '1', 'Provincia WS: planDePago'),
  mapping('provincia', 'rastreador_alarma', 'parametro_9', '0/1', 'Provincia process histórico: Tiene Equipo de Rastreo'),
  mapping('provincia', 'uso', 'bien.40008_uso', 'depende del tipo de vehículo', 'Provincia WS: 40008_uso'),
  mapping('provincia', 'gnc', 'bien.montoAccesorios', '0 o monto', 'Provincia WS: montoAccesorios requerido como total de accesorios'),
  mapping('provincia', 'clausula_ajuste', 'bien.40550_clausulaAjuste', '0/10', 'Provincia WS: 40550_clausulaAjuste valor porcentual'),
  mapping('provincia', 'descuento_comercial', 'bien.40088_bonifAdicional', '1/5/10/15/20/22/25', 'Provincia WS: 40088_bonifAdicional valor porcentual'),
  mapping('provincia', 'comision', 'datosAdicionales.porcentajeComision', '15/20', 'Provincia WS: porcentajeComision valor porcentual; probado 15 y 20 OK'),
  mapping('rivadavia', 'rastreador_alarma', 'datoPoliza.alarmaSatelital', 'SIN_ALARMA/CON_ALARMA', 'Rivadavia request histórico AlarmaSatelital'),
  mapping('rivadavia', 'refacturacion', 'datoPoliza.tipoFacturacion', 'TRIMESTRAL', 'Rivadavia request'),
  mapping('rivadavia', 'cuotas', 'datoPoliza.cantidadCuotas', '3', 'Rivadavia request'),
  mapping('rivadavia', 'uso', 'tipo_uso', 'consulta/tipo_uso', 'Rivadavia Postman consulta/tipo_uso'),
  mapping('rivadavia', 'tipo_vehiculo', 'tipo_vehiculo', '1/6/8', 'Rivadavia infoauto_tipo_vehiculo + consulta codigo_vehiculo'),
  mapping('rivadavia', 'gnc', 'datoPoliza.gnc/sumaAseguradaAccesorios', 'NO_POSEE_GNC/POSEE_GNC + monto', 'Rivadavia API Brokers'),
  mapping('rivadavia', 'clausula_ajuste', 'datoVehiculo.porcentajeAjuste', '30', 'adapter'),
  mapping('rivadavia', 'coeficiente_rc', 'CoefRC', '0.9', 'Rivadavia SOAP histórico wsEmisionPoliza.php'),
  mapping('rivadavia', 'coeficiente_casco', 'CoefCasco', '0.9', 'Rivadavia SOAP histórico wsEmisionPoliza.php'),
  mapping('smg', 'rastreador_alarma', 'nCodLocalizador', '0', 'adapter'),
  mapping('smg', 'refacturacion', 'nCodPeriodo', '6', 'SMG request'),
  mapping('smg', 'cuotas', 'nCantCuotas', '1', 'SMG request'),
  mapping('smg', 'uso', 'nCodUsoVeh', 'obtenerDatosParametricos: Usos del Vehículo', 'SMG WS V1'),
  mapping('smg', 'tipo_vehiculo', 'sTipo_veh', '1=Auto; 2=Moto', 'SMG adapter resolveSmgVehicleType'),
  mapping('smg', 'gnc', 'nMontoGNC', '0 o monto', 'SMG request'),
  mapping('smg', 'clausula_ajuste', 'nCodClausulaAjuste', '1=S/C; 2=10%; 3=20%', 'WS SMG V1 Tabla 1'),
  mapping('smg', 'descuento_comercial', 'nAjustePrima', '-15', 'adapter'),
  mapping('smg', 'asistencia', 'AsistMecanica', '-1=Sí; 0=No', 'SMG WS + histórico process_SMG'),
  mapping('smg', 'plan_comercial', 'cod_tipo_poliza', '1=Plan Normal', 'SMG request'),
  mapping('sancor', 'garage_guardado', 'ScoringOptions[typeId=3].SelectedOptionId', '1=Sí; 2=No', 'Sancor Cotizar Automotores Request.xml'),
  mapping('victoria', 'clausula_ajuste', 'policy.adjustment_clause', '1=0%; 2=10%; 3=20%; 4=30%', 'Victoria obtenerClausulasAjuste'),
  mapping('victoria', 'variacion_32080', 'policy.variation_32080_code', '1=-15%; 6=-10%; 11=-5%; 16=0%; 21=5%; 26=10%', 'Victoria obtenerVariacion32080'),
  mapping('victoria', 'refacturacion', 'vigencia.id', 'obtenerVigencias + tipoFacturacion', 'Victoria adapter /cea/reference/obtenerVigencias'),
  mapping('victoria', 'cuotas', 'planCuota.cantidadCuotas', 'obtenerCantidadCuotas(vigencia, formaPago)', 'Victoria adapter /cea/reference/obtenerCantidadCuotas'),
  mapping('victoria', 'rastreador_alarma', 'vehicle.satellite_tracking/vehicle.sistem_tracking', 'false|0 o true|prestador', 'MultiPas'),
  mapping('victoria', 'uso', 'vehicle.use', '1=Particular; 2=Comercial; 8=Transporte de bienes; 9=Trabajos rurales', 'MultiPas'),
  mapping('victoria', 'gnc', 'vehicle.gnc', 'false/true', 'MultiPas'),
  mapping('victoria', 'descuento_comercial', 'vehicle.discount_commercial', 'negativo=descuento, positivo=recargo', 'MultiPas'),
  mapping('victoria', 'descuento_seguro_nuevo', 'vehicle.discount_new_insurance', '25', 'MultiPas'),
  mapping('meridional', 'medio_pago', 'medioPago', 'Tarjeta de crédito', 'PPT'),
  mapping('meridional', 'refacturacion', 'IdPeriodo', '4=cuatrimestral', 'Meridional Condiciones Comerciales + adapter'),
  mapping('meridional', 'cuotas', 'CantidadCuotas', '4', 'Meridional Condiciones Comerciales + adapter'),
  mapping('meridional', 'rastreador_alarma', 'IdRastreador', '1/16/17/23/24/25/26/32/33', 'Meridional WSCAR + diccionario local'),
  mapping('meridional', 'uso', 'Vehiculos.IdUsoVehiculo', '1/2/4/5/28/29', 'Meridional PARAMETRICAS.xlsx'),
  mapping('meridional', 'ocupacion', 'ocupacion', 'No informa', 'PPT'),
  mapping('meridional', 'gnc', 'Vehiculos.Accesorios.IdAccesorio/SumaAseguradaAccesorio', 'ACCESSORY_GNC + monto', 'Meridional WSCAR cotización: accesorios por catálogo'),
  mapping('meridional', 'clausula_ajuste', 'IdClausulaAjuste', '1=0%; 2=20%; 3=30%; 4=40%; 5=50%', 'Meridional GetAllClausulasAjuste + data/meridional/diccionarios/clausula_ajuste.json'),
  mapping('meridional', 'comision', 'PorcComision', '18', 'Meridional WSCAR cotización: PorcComision'),
];

function concept(code, label, group, uiType, overrideRole, description) {
  return {
    id: code,
    code,
    label,
    group,
    ui_type: uiType,
    active: true,
    supports_default_autoiq: true,
    supports_default_seguros911: true,
    quote_override_role: overrideRole,
    description,
  };
}

function value(company_slug, concept_code, visible_value, ws_code = null, numeric_value = null) {
  return {
    owner_type: 'profile',
    owner_id: 'default_seguros911',
    company_slug,
    concept_code,
    visible_value,
    ws_code,
    numeric_value,
    source: 'matriz_funcional_v2',
  };
}

function rule(company_slug, concept_code, min_role, allowed, min, max, notes) {
  return {
    company_slug,
    concept_code,
    min_role,
    allowed,
    min,
    max,
    notes,
  };
}

function mapping(company_slug, concept_code, ws_field, ws_code, source) {
  return {
    company_slug,
    concept_code,
    ws_field,
    ws_code,
    source,
  };
}

function option(company_slug, concept_code, visible_label, ws_code = null, numeric_value = null) {
  return {
    company_slug,
    concept_code,
    visible_label,
    ws_code,
    numeric_value,
    active: true,
  };
}

function optionsFromList(companySlug, conceptCode, entries) {
  const seen = new Set();
  return entries
    .map(([visibleLabel, wsCode, numericValue = null]) => option(companySlug, conceptCode, visibleLabel, wsCode, numericValue))
    .filter((item) => {
      const key = `${item.company_slug}:${item.concept_code}:${item.visible_label}:${item.ws_code}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });
}

function buildDefaultStore(now = new Date().toISOString()) {
  return {
    version: 26,
    updated_at: now,
    companies: ACTIVE_COMPANIES,
    concepts: CONCEPTS,
    profiles: [
      {
        id: 'default_seguros911',
        code: 'DEFAULT_SEGUROS911',
        label: 'Default Seguros911',
        profile_type: 'default',
      },
    ],
    producers: [],
    users: [
      {
        id: 'superadmin-local',
        source_system: 'autoiq',
        external_user_id: 'superadmin-local',
        display_name: 'Super Admin',
        email: 'superadmin@autoiq.local',
        role: 'superadmin',
        active: true,
      },
    ],
    user_company_settings: [],
    values: DEFAULT_VALUES,
    options: OPTIONS,
    override_rules: OVERRIDE_RULES,
    ws_mappings: WS_MAPPINGS,
    quote_overrides: [],
  };
}

module.exports = {
  ACTIVE_COMPANIES,
  CONCEPTS,
  DEFAULT_VALUES,
  OPTIONS,
  OVERRIDE_RULES,
  WS_MAPPINGS,
  buildDefaultStore,
};
